title: Sonia Fereidooni
logo: /assets/img/profilephoto.png
# description: My name is Sonia, and I'm a dedicated and collaborative Computer Science Junior at UCSD. I'm seeking to spur technological innovation with an emphasis on Software Engineering and Artificial Intelligence. I'm passionate about learning and growing, and I am thrilled to be a part of the dynamic and innovative team at Dr. Rose Yu's Spatiotemporal Learning Lab. My goal is to make a meaningful contribution to the field of computer science and push the boundaries of what's possible. Thank you for taking the time to visit my personal portfolio website, and please feel free to reach out to me with any questions or comments!
description: Undergraduate Student<br>UC San Diego<br>B.S. Computer Science
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
